"use client";

import { useState } from "react";

/**
 * Labels where the text came from. Demo output is scripted, not model output,
 * and must never be badged as AI-generated.
 */
export function AiBadge({ mode }: { mode?: "demo" | "live" | null }) {
  const demo = mode === "demo";
  const color = demo ? "var(--color-text-muted)" : "var(--color-accent)";
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[0.65rem] font-semibold uppercase tracking-[0.08em]"
      style={{ background: `color-mix(in srgb, ${color} 14%, transparent)`, color }}
      title={
        demo
          ? "Scripted sample response - no model was called. Add an API key for live analysis."
          : "Generated by Claude from the operating data."
      }
    >
      <svg width="10" height="10" viewBox="0 0 12 12" aria-hidden="true">
        <path d="M6 0 L7.4 4.6 L12 6 L7.4 7.4 L6 12 L4.6 7.4 L0 6 L4.6 4.6 Z" fill="currentColor" />
      </svg>
      {demo ? "Sample response" : mode === "live" ? "AI generated" : "AI"}
    </span>
  );
}

/** Consistent unavailable/error state for every AI surface. */
export function AiUnavailable({ reason }: { reason: string }) {
  return (
    <div className="hq-card p-5">
      <p className="text-sm font-medium">AI features are switched off</p>
      <p className="mt-1.5 text-sm text-[color:var(--color-text-muted)]">{reason}</p>
      <pre className="mt-3 overflow-x-auto rounded-[var(--radius-sm)] bg-[color:var(--color-bg)] p-3 font-mono text-xs">
{`# airporthq-platform/.env.local
ANTHROPIC_API_KEY=sk-ant-...`}
      </pre>
    </div>
  );
}

export function useAiCall<T extends { mode?: "demo" | "live" }>(endpoint: string) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [unavailable, setUnavailable] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function run(body?: unknown) {
    setLoading(true);
    setError(null);
    setUnavailable(null);
    try {
      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body ?? {}),
      });
      const json = await res.json();
      if (json.unavailable) setUnavailable(json.reason);
      else if (!res.ok) setError(json.error ?? `Request failed (${res.status})`);
      else setData(json as T);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Request failed");
    } finally {
      setLoading(false);
    }
  }

  return { data, error, unavailable, loading, run };
}
